name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          extras_css: |
            h2 {
              color: red;
            }
          plugin_isocalendar: yes
          plugin_languages: yes
          config_timezone: Asia/Kuala_Lumpur
          config_order: base.header, isocalendar, languages
          token: ${{ secrets.METRICS }}
